#!/usr/bin/env node
// Generates src/legal.ts from the canonical markdown in docs/legal/.
// Never hand-edit src/legal.ts — run `pnpm embed:legal` instead.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../../..');
const OUT = resolve(HERE, '../src/legal.ts');

const EFFECTIVE = 'September 1, 2026';
const LEGAL_VERSION = '2026-09';

const esc = (s) => s.replace(/[&<>]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' })[c]);
const isHeading = (l) => /^(\d+\.\s|[A-Z]\.\s|Section \d+|Office Use Only$)/.test(l);

function toHtml(md) {
  const src = md.replace(/\[EFFECTIVE DATE\]/g, EFFECTIVE).replace(/\[REVIEW DATE\]/g, EFFECTIVE);
  const out = [];
  let inList = false;
  for (const raw of src.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;
    const bullet = /^[•\-*]\s*/.test(line);
    if (bullet && !inList) { out.push('<ul>'); inList = true; }
    if (!bullet && inList) { out.push('</ul>'); inList = false; }
    if (bullet) out.push(`<li>${esc(line.replace(/^[•\-*]\s*/, ''))}</li>`);
    else if (isHeading(line)) out.push(`<h4>${esc(line)}</h4>`);
    else out.push(`<p>${esc(line)}</p>`);
  }
  if (inList) out.push('</ul>');
  return out.join('');
}

const read = (f) => readFileSync(resolve(REPO, 'docs/legal', f), 'utf8');
const npp = toHtml(read('My_4M_Life_Notice_of_Privacy_Practices.md'));
const auth = toHtml(read('My_4M_Life_Patient_Authorization.md'));
const lit = (s) => '`' + s.replace(/[\\`$]/g, (c) => '\\' + c) + '`';

writeFileSync(OUT, `// GENERATED by scripts/embed-legal.mjs from docs/legal/*.md — do not edit by hand.
export const LEGAL_VERSION = '${LEGAL_VERSION}';
export const LEGAL_EFFECTIVE = '${EFFECTIVE}';
export const NPP_HTML = ${lit(npp)};
export const PATIENT_AUTH_HTML = ${lit(auth)};
`);
console.log(`Wrote ${OUT} (npp ${npp.length}b, auth ${auth.length}b)`);
