import type { Resource } from '../data/schema';

/**
 * A single 4M Mitigate audit factor. Content is authored here and consumed
 * by Svelte components — no content lives in .svelte files.
 */
export interface Factor {
  /** Two-character id (e.g. "00", "08b"). */
  n: string;
  name: string;
  sub?: string;
  /** Badge tag, e.g. "IMMUNE" or "Keto-Paleo". */
  tag?: string | null;
  /** Tag/accent color hex. */
  tc?: string;
  /** Connected Mind flag — shows special assessment banner. */
  cm?: boolean;
  /** Immediate actions bullets. */
  imm?: string[];
  /** Legacy "action" bullets (for factors 00 / 08b that predate the imm/tools split). */
  act?: string[];
  /** "Tools" tab bullets (was `.tools`). */
  tools?: string[];
  /** Advanced tab bullets. */
  adv?: string[];
  /** Resource links. */
  res: Resource[];
}

export const factors: Factor[] = [
  { n:'00', name:'Allergies & immune reactivity', tag:'IMMUNE', tc:'#9B4D8A',
    act:['List all known food allergies and sensitivities (gluten, dairy, nuts, shellfish, etc.)',
         'Note environmental allergies — pollen, mold, dust mites, pet dander',
         'Consider that undiagnosed food sensitivities drive gut inflammation and leaky gut',
         'An elimination diet (remove top 8 allergens for 3 weeks) is the gold standard for identification',
         'Allergic load = immune burden = neuroinflammatory risk — reducing it is brain optimization'],
    imm:['Request an IgE and IgG food sensitivity panel from your physician',
         'Start a 3-day food/symptom journal — track what you eat and how you feel 30–60 min after',
         'Remove known allergens completely for 30 days — not partially'],
    adv:['Chronic allergic load increases cortisol and histamine — both impair sleep and cognition',
         'Leaky gut and food sensitivities are tightly linked — gut repair in Week 1 addresses root cause',
         'Consider working with a functional medicine provider on full allergy/sensitivity testing'],
    res:[{n:'FARE — Food Allergy Research & Education',u:'https://www.foodallergy.org'},
         {n:'Viome — gut and immune testing',u:'https://www.viome.com'}] },
  { n:'01', name:'Mental health & mental wellness', tag:'Connected Mind', tc:'#2E7FD9',
    sub:'Anxiety, depression, mood instability, or unaddressed trauma', cm:true,
    imm:['Complete the Connected Mind assessment BEFORE scoring this factor',
         'Rate your current mood, anxiety, and emotional stability honestly — this is private',
         'Practice box breathing right now: 4 in, hold 4, out 4, hold 4 — repeat 4 times',
         'Identify one recurring thought pattern that most disrupts your mental wellness'],
    tools:['Depression and anxiety directly accelerate neuroinflammation and cognitive decline',
           'Many 4M interventions are direct mental health tools: sleep, exercise, cold exposure, purpose',
           'Magnesium, omega-3, and methylated B-complex all have peer-reviewed mood support evidence',
           'The gut-brain axis is bidirectional — improving gut health improves mental health directly'],
    adv:['Working with a therapist is the highest-leverage intervention for persistent symptoms',
         'Track mood, anxiety, and focus weekly using the 1–10 self-rating scale throughout',
         'This program addresses root causes — every 4M pillar is a mental health intervention'],
    res:[{n:'Psychology Today — find a therapist',u:'https://www.psychologytoday.com/us/therapists'},
         {n:'NAMI Helpline',u:'https://www.nami.org/help'},
         {n:'Huberman Lab — depression & anxiety tools',u:'https://hubermanlab.com'}] },
  { n:'02', name:'Gut microbiome health', tag:null,
    sub:'Bloating, irregular digestion, processed food diet, or frequent antibiotic use',
    imm:['Add one fermented food today: Greek yogurt, kefir, sauerkraut, or kimchi',
         'Replace one ultra-processed snack with a high-fiber whole food this week',
         'Practice box breathing after meals — digestion is optimal in parasympathetic state',
         'Drink 8–16 oz bone broth daily — glycine and collagen repair the gut lining directly'],
    tools:['Your gut and brain communicate directly via the vagus nerve — 24 hours a day',
           'Aim for 30 different plant foods per week — diversity is the medicine here',
           'Your gut produces 90% of your serotonin — mood is a gut issue as much as a brain issue',
           'P. gingivalis from poor oral health can enter the gut and worsen dysbiosis — factors 02 and 03 are linked'],
    adv:['Consider Viome or Genova GI Effects comprehensive gut testing',
         'Rule out SIBO or leaky gut with your physician if issues are persistent',
         'Avoid unnecessary antibiotics and NSAIDs — both cause lasting microbiome damage'],
    res:[{n:'Viome gut testing',u:'https://viome.com'},
         {n:'Seed DS-01 probiotic',u:'https://seed.com'},
         {n:'ZOE nutrition program',u:'https://zoe.com'}] },
  { n:'03', name:'Poor dental health & oral microbiome', tag:'Oral · Brain · Heart', tc:'#D4920A',
    sub:'Gum disease, bleeding gums, poor hygiene, or no recent dental cleaning',
    imm:['Schedule a dental cleaning this month — one annual cleaning reduces cardiovascular risk by 14%',
         'Brush twice daily with a remineralizing toothpaste — before bed is the most critical session',
         'Floss every night — gum disease begins in the spaces your toothbrush cannot reach',
         'Oil pull with coconut oil for 10 minutes each morning to reduce oral bacterial load',
         'Scrape your tongue daily — this removes bacterial biofilm where pathogens accumulate'],
    tools:["P. gingivalis travels from leaky gums to the brain — detected in Alzheimer's brain tissue post-mortem",
           "Meta-analysis: 10× higher Alzheimer's risk when oral bacteria are found in brain tissue",
           'The same periodontal pathogens clog arteries, elevate CRP, and impair endothelial function',
           'YOU NEED A STRONG HEART TO HAVE A STRONG BRAIN — cardiovascular health IS brain health',
           'Blood carries oxygen to neurons — compromised cardiac function means compromised cognition',
           'One dental cleaning per year independently reduces cardiovascular risk by 14%',
           'One daily toothbrushing reduces cardiovascular risk by 9%'],
    adv:['Find a biological or holistic dentist — they treat oral health as whole-body health',
         'Request a salivary microbiome test to identify your specific oral pathogens',
         'Oral probiotics (S. salivarius K12 and M18) competitively displace harmful bacteria',
         'Periodontal therapy has been shown to reduce systemic CRP and improve endothelial function'],
    res:[{n:'IAOMT — find a biological dentist',u:'https://iaomt.org/for-patients/search/'},
         {n:'American Academy of Periodontology',u:'https://perio.org/for-patients'},
         {n:'IFM — oral microbiome & cardiometabolic',u:'https://ifm.org'},
         {n:'Huberman Lab — oral health protocol',u:'https://hubermanlab.com'}] },
  { n:'04', name:'Sunlight & vitamin D', tag:null,
    sub:'Less than 20 min daily outdoor exposure, known D deficiency, or mostly indoor lifestyle',
    imm:['Get outside within 60 minutes of waking — no sunglasses — 10–20 minutes minimum',
         'Order a vitamin D blood test — no prescription needed at most walk-in labs',
         'Stack sunlight time with box breathing and morning movement simultaneously'],
    tools:['Vitamin D is a steroid hormone regulating over 2,000 genes including brain protection pathways',
           'Target serum level: 50–80 ng/mL — most men over 35 test at 20–30 without knowing',
           'Always pair D3 with K2 (100mcg) to direct calcium to bones and not arteries',
           'Morning sunlight sets your circadian rhythm independently of vitamin D — both matter'],
    adv:['Test again 90 days after supplementing to confirm levels have normalized',
         'Magnesium is required to convert D3 to its active hormonal form — take both',
         'Use a UVB lamp in winter if you live above 35 degrees latitude'],
    res:[{n:'GrassrootsHealth D*Action',u:'https://grassrootshealth.net'},
         {n:'Examine.com — Vitamin D',u:'https://examine.com/supplements/vitamin-d/'},
         {n:'Huberman Lab — light & circadian rhythm',u:'https://hubermanlab.com'}] },
  { n:'05', name:'Alcohol consumption', tag:null,
    sub:'More than 7 drinks per week, binge drinking, or drinking nightly to unwind',
    imm:['Track every drink for 7 days — no judgment, just honest honest data to work from',
         'Identify your primary trigger: stress, habit, social pressure, or boredom',
         'Practice box breathing when a craving hits — it is the fastest cortisol intervention available'],
    tools:['Alcohol crosses the blood-brain barrier and directly damages neurons with every drink',
           'Disrupts sleep architecture and destroys REM sleep — even one drink affects deep sleep quality',
           'Raises cortisol, inflames the gut lining, and shrinks the hippocampus with chronic use',
           'Over 7 drinks per week is the clinical threshold where neurological risk accelerates measurably'],
    adv:['Consider a 30-day alcohol-free challenge — Dry January or Sober October as entry points',
         'Try the Reframe or I Am Sober apps for guided reduction and accountability',
         'If drinking feels uncontrollable, speak with your physician — this is medical not moral'],
    res:[{n:'Reframe app',u:'https://reframeapp.com'},
         {n:'Dry January',u:'https://dryjanuary.org.uk'},
         {n:'Huberman Lab — alcohol & the brain',u:'https://hubermanlab.com'}] },
  { n:'06', name:'Sleep quality & duration', tag:null,
    sub:'Less than 7 hours most nights, poor quality, frequent waking, or no consistent schedule',
    imm:['Set a fixed wake time and hold it 7 days per week — including weekends without exception',
         'Get 10 minutes of outdoor light within 60 minutes of waking — this anchors your circadian clock',
         'Take 400mg magnesium glycinate 30 minutes before bed starting tonight'],
    tools:['The glymphatic system flushes amyloid beta plaques during deep sleep — and only during deep sleep',
           'Less than 7 hours means your brain does not complete its full nightly cleaning cycle',
           'One night of poor sleep measurably elevates amyloid beta the following day',
           'Consistent wake time is more powerful than consistent bedtime for circadian anchoring'],
    adv:['Consider a sleep study if you snore heavily, wake gasping, or feel unrefreshed consistently',
         'Avoid caffeine after 12pm — it has a 5–7 hour half-life and disrupts sleep architecture',
         'No alcohol within 3 hours of sleep — it completely destroys REM sleep stages'],
    res:[{n:'Huberman Lab sleep toolkit',u:'https://hubermanlab.com/newsletter/toolkit-for-sleep'},
         {n:'Sleep Foundation',u:'https://sleepfoundation.org'},
         {n:'Oura Ring',u:'https://ouraring.com'}] },
  { n:'07', name:'Poor nutrition quality', tag:'Keto-Paleo', tc:'#1D9E75',
    sub:'Ultra-processed food, poor animal food quality, or chronic under-eating protein',
    imm:['Set your eating window now: first meal after 9am (after morning routine), last meal by 7pm — work toward moving to 6pm, then 5pm over time',
         'Do your morning routine completely fasted — water or black coffee only, nothing else',
         'Swap one meal this week to grass-fed beef, wild game, or wild-caught salmon',
         'Eliminate ALL seed oils immediately: canola, soybean, corn, sunflower, safflower',
         'Try Force of Nature ancestral blend this week as your organ meat introduction'],
    tools:['Build every meal around high-quality animal protein — grass-fed, wild game, wild fish',
           'Cook exclusively in animal fats: tallow, lard, ghee, duck fat, or grass-fed butter',
           'Protein target: target bodyweight (lbs) × 0.9 = your daily gram requirement',
           'Bone broth daily — collagen, glycine, and gut lining repair in every cup'],
    adv:['Explore nose-to-tail eating: beef liver 1–2x per week is the Month 2 nutritional target',
         'Source from grass-fed suppliers: ButcherBox, US Wellness Meats, Vital Choice',
         'Month 2 extends fast to 16:8 — first meal after 11am as metabolic flexibility builds',
         'Month 3 moves to 18:6 fasting — by then most men find extended fasting surprisingly easy'],
    res:[{n:'ButcherBox — grass-fed beef & wild salmon',u:'https://butcherbox.com'},
         {n:'US Wellness Meats — organ meats & game',u:'https://uswellnessmeats.com'},
         {n:'Force of Nature — ancestral blend',u:'https://forceofnaturemeats.com'},
         {n:'Vital Choice — wild-caught seafood',u:'https://vitalchoice.com'},
         {n:'Ancestral Supplements — organ capsules',u:'https://ancestralsupplements.com'}] },
  { n:'08', name:'Physical inactivity & injuries', tag:'KOT', tc:'#D85A30',
    sub:'Not exercising regularly, or chronic injuries preventing consistent movement',
    imm:['Schedule your 3 training days in your calendar right now — these are non-negotiable',
         'Start your morning movement stack tomorrow: fireside squat, sumo squat, lunge, hip circles',
         'If injured, identify which movements you CAN do safely — movement always beats rest'],
    tools:['Resistance training elevates BDNF by up to 300% — Miracle-Gro for your neurons',
           'KOT system: knees over toes is the solution to chronic joint pain, not the problem',
           '3 training days + 2 Zone 2 walks per week is your complete weekly movement protocol',
           'Zone 2 cardio builds mitochondrial density and independently elevates BDNF'],
    adv:['BPC-157 has emerging peer-reviewed evidence for tendon and joint repair',
         'Physical therapy for any injury limiting you 3+ months is worth every dollar',
         'The KOT morning protocol progression builds long-term joint health systematically'],
    res:[{n:'KOT Beginner Playlist — Ben Patrick',u:'https://www.youtube.com/c/TheKneesovertoesguy'},
         {n:'Examine.com — BPC-157',u:'https://examine.com/supplements/bpc-157/'},
         {n:'APTA — Find a physical therapist',u:'https://choosept.com'}] },
  { n:'08b', name:'Injury history & joint health', tag:'JOINTS', tc:'#C04A20',
    act:['List all current injuries, surgeries, or chronic pain areas honestly',
         'Joint pain is a signal — inflammation is upstream of injury and must be addressed',
         'KOT system: knees over toes is the long-term solution to joint degeneration',
         'Begin tibialis anterior work and reverse Nordic progressions — Ben Patrick fundamentals',
         'Consider whether unresolved injuries are limiting your training and quality of life'],
    res:[{n:'KOT Channel — Ben Patrick',u:'https://www.youtube.com/c/TheKneesovertoesguy'},
         {n:'ATG Online Coaching',u:'https://www.atgonlinecoaching.com'}] },
  { n:'09', name:'Chronic stress', tag:null,
    sub:'Persistent work, financial, or relationship stress — cortisol chronically elevated',
    imm:['Name your single biggest cortisol driver — write it down specifically and precisely right now',
         'Add one 10-minute daily decompression ritual: walk, breathwork, or complete silence',
         'Practice box breathing any time stress spikes: 4 in, hold 4, out 4, hold 4'],
    tools:['Chronically elevated cortisol literally shrinks the hippocampus — this is measurable on MRI',
           'Cortisol disrupts sleep, inflames the gut, suppresses testosterone, and impairs memory formation',
           'Reduce phone notifications by 50% today — digital overstimulation chronically elevates cortisol'],
    adv:['Phosphatidylserine 100–300mg daily helps blunt the cortisol response directly',
         'HRV tracking measures your stress recovery objectively — Whoop or Garmin are best in class',
         'Adaptogens: ashwagandha and rhodiola both have peer-reviewed cortisol-modulating evidence'],
    res:[{n:'Huberman Lab — stress & anxiety tools',u:'https://hubermanlab.com'},
         {n:'HeartMath HRV biofeedback',u:'https://heartmath.com'},
         {n:'Calm app',u:'https://calm.com'}] },
  { n:'10', name:'Excess body fat', tag:null,
    sub:'Significant visceral or abdominal fat — waist over 40 in, or body fat over 25%',
    imm:['Measure your waist at the navel right now and record that number in your workbook',
         'Calculate your protein target: target bodyweight (lbs) × 0.9 = daily grams',
         'Cut one ultra-processed food from your daily routine starting today'],
    tools:['Visceral fat is metabolically active — it produces cytokines that cross the blood-brain barrier',
           'Waist circumference at the navel is your best daily proxy for visceral fat — not the scale',
           'The 3-day training protocol directly targets visceral fat via improved insulin sensitivity',
           'Resistance training + high protein targets visceral fat faster than caloric restriction alone'],
    adv:['A DEXA scan or InBody scan gives accurate and actionable body fat percentage',
         'If waist is over 40 inches, request metabolic bloodwork: HbA1c, fasting insulin, triglycerides',
         'Visceral fat responds rapidly to the combined 4M protocol — expect significant change by Day 60'],
    res:[{n:'InBody scan locator',u:'https://inbodyusa.com/pages/find-a-location'},
         {n:'Peter Attia — metabolic health',u:'https://peterattiamd.com'},
         {n:'DEXA scan locator',u:'https://dexascan.com'}] },
  { n:'11', name:'Social isolation & lack of purpose', tag:null,
    sub:'Limited meaningful connection, or absence of goals that genuinely excite you',
    imm:['Reach out to one person you have been meaning to connect with this week — today',
         'Write down one goal that genuinely excites you for the next 90 days',
         'Introduce yourself actively in the 4M cohort group before the next live call'],
    tools:['Loneliness raises dementia risk as much as smoking 15 cigarettes per day — peer-reviewed',
           'Purpose activates the prefrontal cortex and keeps dopamine systems calibrated with age',
           'The Waldorf study found social connection is the single strongest predictor of cognitive health at 80',
           'This cohort is itself a direct intervention for this risk factor — use it actively not passively'],
    adv:["If isolation feels entrenched, consider a therapist or a structured men's accountability group",
         "Ikigai: find the overlap of what you love, what you're good at, what the world needs, and what pays",
         'The 4M alumni community at graduation directly addresses this factor long-term'],
    res:[{n:'Meetup.com',u:'https://meetup.com'},
         {n:'Good Men Project',u:'https://goodmenproject.com'}] },
  { n:'12', name:'Cognitive disengagement', tag:null,
    sub:'No learning, reading, creative hobbies, or mentally stimulating activities daily',
    imm:['Commit to 30 minutes of uninterrupted reading today — no phone, no TV, no interruptions',
         'Download a dual n-back app and complete your first session this week',
         'Identify one new skill you want to start learning this month and write it down'],
    tools:['Neural circuits that are not regularly activated begin to prune — use it or lose it is literal biology',
           'Dual n-back is the only cognitive training with peer-reviewed transfer to real-world intelligence',
           'Long-form reading rebuilds the sustained attention capacity that digital media has systematically eroded',
           "Cognitive reserve built over years is your best protection against Alzheimer's onset"],
    adv:['Take a language class, chess course, or music lesson — novelty drives neuroplastic change',
         'Track cognitive performance weekly: rate focus, memory, and mood each 1–10 every Sunday evening',
         'The combination of dual n-back + long-form reading is the most evidence-backed cognitive protocol available'],
    res:[{n:'Dual N-Back app (iOS)',u:'https://apps.apple.com/us/app/dual-n-back/id507031600'},
         {n:'Duolingo',u:'https://duolingo.com'},
         {n:'Lumosity',u:'https://lumosity.com'}] }
];
