/**
 * LDRGLPRx diagnostic lab panels.
 * Content only — no logic.
 */

import type { LabPanel } from '../data/catalog';

export const labs: LabPanel[] = [
  {
    id: 'lab-foundation',
    slug: 'lab-foundation',
    name: 'Foundation Panel',
    category: 'lab',
    tagline: 'Comprehensive metabolic and nutritional baseline for every new member.',
    description:
      'A broad metabolic, thyroid, cardiovascular, and nutritional panel covering the key biomarkers required before any protocol personalisation.',
    mechanismBullets: [
      'Metabolic panel identifies glucose dysregulation, liver and kidney function',
      'ApoB provides better cardiovascular risk signal than LDL-C alone',
      'Full thyroid axis (TSH/fT3/fT4/rT3/TPO/Tg) catches conversion and autoimmune issues missed by TSH alone',
      'Fasting insulin + HOMA-IR detects insulin resistance before glucose thresholds are breached',
      'MTHFR genotyping informs methylation protocol and supplement selection',
    ],
    indications: [
      'Supports baseline health assessment and protocol personalisation',
      'Helps with identifying subclinical metabolic and nutritional deficiencies',
    ],
    tests: [
      'CMP (comprehensive metabolic panel)',
      'CBC with differential',
      'Lipid panel',
      'ApoB',
      'hs-CRP',
      'TSH',
      'Free T3',
      'Free T4',
      'Reverse T3',
      'TPO antibodies',
      'Thyroglobulin antibodies',
      'Vitamin D (25-OH)',
      'Vitamin B12',
      'Ferritin',
      'Fasting insulin',
      'HOMA-IR (calculated)',
      'Omega-3 index',
      'MTHFR C677T',
      'MTHFR A1298C',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 249,
      memberUSD: 199,
    },
    requiresRx: false,
    vendor: 'Rupa',
    fulfilledBy: 'Rupa Health',
    tierAvailability: {
      foundation: 'included',
      optimization: 'included',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['general_wellness', 'new_member_onboarding'],
    tags: ['lab', 'baseline', 'metabolic', 'thyroid', 'foundation'],
  },

  {
    id: 'lab-cognitive-baseline',
    slug: 'lab-cognitive-baseline',
    name: 'Cognitive Baseline',
    category: 'lab',
    tagline: 'Validated digital cognitive assessment for objective brain performance tracking.',
    description:
      'Creyos digital cognitive assessment providing normed scores across memory, attention, executive function, and processing speed — establishes a quantified baseline for tracking cognitive response to protocols.',
    mechanismBullets: [
      'Scientifically validated battery with population-normed percentile scores',
      'Sensitive to cognitive change over time — suitable for repeat measurement',
      'Covers domains: episodic memory, working memory, attention, processing speed, reasoning',
    ],
    indications: [
      'Supports objective cognitive baseline for longevity and optimisation tracking',
      'Helps with identifying cognitive domains most in need of intervention',
    ],
    tests: [
      'Spatial planning (Tower of London)',
      'Digit span (working memory)',
      'Word recall (episodic memory)',
      'Spatial working memory',
      'Attention and processing speed',
      'Composite cognitive score',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 49,
      memberUSD: 39,
    },
    requiresRx: false,
    vendor: 'Creyos',
    fulfilledBy: 'Creyos',
    tierAvailability: {
      foundation: 'included',
      optimization: 'included',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['new_member_onboarding', 'cognitive_concern'],
    tags: ['lab', 'cognitive', 'digital', 'baseline', 'creyos'],
  },

  {
    id: 'lab-gut-brain',
    slug: 'lab-gut-brain',
    name: 'Gut + Brain Panel',
    category: 'lab',
    tagline: 'Comprehensive gut-brain axis mapping across microbiome, permeability, and neurochemistry.',
    description:
      'Multi-vendor panel combining GI-MAP stool PCR, SIBO breath test, organic acids (OAT), zonulin, oral microbiome, and serum BDNF to characterise the full gut-brain axis.',
    mechanismBullets: [
      'GI-MAP (PCR) quantifies pathogenic, commensal, and dysbiotic organisms with high sensitivity',
      'SIBO breath test identifies small intestinal overgrowth (hydrogen and methane)',
      'OAT (organic acids) reveals mitochondrial, neurotransmitter, and nutritional metabolite patterns',
      'Zonulin is the primary biomarker for intestinal permeability (leaky gut)',
      'Bristle oral microbiome identifies upstream dysbiosis affecting systemic inflammation',
      'Serum BDNF quantifies neurotrophin output as a gut-brain axis functional marker',
    ],
    indications: [
      'Helps with identifying root causes of gut-brain axis dysfunction',
      'Supports protocol design for IBS, brain fog, mood, and microbiome repair',
    ],
    tests: [
      'GI-MAP stool PCR (Diagnostic Solutions)',
      'SIBO lactulose breath test (hydrogen + methane)',
      'Organic acids test — OAT (Mosaic Diagnostics)',
      'Zonulin (serum or stool)',
      'Oral microbiome profile (Bristle)',
      'BDNF (serum)',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 899,
      memberUSD: 749,
    },
    requiresRx: false,
    vendor: 'Diagnostic Solutions',
    fulfilledBy: 'Multiple — Diagnostic Solutions, Mosaic, Bristle',
    tierAvailability: {
      foundation: 'addon',
      optimization: 'included',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['gut_symptoms', 'brain_fog', 'ibs', 'microbiome_concern'],
    tags: ['lab', 'gut', 'microbiome', 'bdnf', 'oat', 'gimap'],
  },

  {
    id: 'lab-genomic-blueprint',
    slug: 'lab-genomic-blueprint',
    name: 'Genomic Blueprint',
    category: 'lab',
    tagline: 'One-time SNP panel covering methylation, APOE, pharmacogenomics, and nutrigenomics.',
    description:
      'Comprehensive once-in-a-lifetime genomic panel including full methylation pathway SNPs, APOE genotyping, CYP450 pharmacogenomics, detox pathway SNPs, and nutrigenomic variants.',
    mechanismBullets: [
      'Methylation SNPs (COMT, MTR, MTRR, CBS, BHMT, AHCY, MAO-A) guide supplement protocol individualisation',
      'APOE genotyping quantifies Alzheimer\'s and cardiovascular risk with precision',
      'CYP2D6/2C19/3A4 pharmacogenomics prevents adverse drug reactions and guides Rx dosing',
      'Detox SNPs (GST, SOD2, NQO1) inform environmental exposure risk and sulforaphane dosing',
      'Nutrigenomic variants guide dietary and micronutrient interventions',
    ],
    indications: [
      'Supports lifetime personalisation of nutrition, supplements, and Rx protocols',
      'Helps with identifying genetic contributors to cognitive risk, detox capacity, and metabolism',
    ],
    tests: [
      'COMT V158M',
      'MTR A2756G',
      'MTRR A66G',
      'CBS C699T',
      'BHMT G742A',
      'AHCY SNPs',
      'MAO-A R297R',
      'APOE ε2/ε3/ε4',
      'CYP2D6 (key variants)',
      'CYP2C19 (key variants)',
      'CYP3A4 (key variants)',
      'GST (GSTM1, GSTT1)',
      'SOD2 V16A',
      'NQO1 P187S',
      'Nutrigenomic panel (VDR, FADS1, FTO, TCF7L2, and others)',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 599,
      memberUSD: 499,
    },
    requiresRx: false,
    vendor: 'Quest',
    fulfilledBy: 'Quest / specialty genomics lab',
    tierAvailability: {
      foundation: 'addon',
      optimization: 'included',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['new_member_onboarding', 'cognitive_concern', 'longevity_focus'],
    tags: ['lab', 'genomics', 'methylation', 'apoe', 'pgx', 'one-time'],
  },

  {
    id: 'lab-hormone-optimization',
    slug: 'lab-hormone-optimization',
    name: 'Hormone Optimisation Panel',
    category: 'lab',
    tagline: 'Full male/female hormone panel including DUTCH and IGF-1.',
    description:
      'Comprehensive serum hormone panel combined with the DUTCH urine test and IGF-1; covers sex hormones, adrenal function, cortisol metabolites, and growth hormone axis.',
    mechanismBullets: [
      'Serum panel captures circulating total and free hormones with precision',
      'DUTCH (dried urine) reveals hormone metabolites, cortisol rhythms, and estrogen detox pathways',
      'IGF-1 is the primary marker for growth hormone axis activity',
      'Combined serum + DUTCH provides a complete picture unavailable from either alone',
    ],
    indications: [
      'Supports hormone optimisation protocol design for TRT, HRT, and adrenal support',
      'Helps with identifying suboptimal hormone levels and metabolite imbalances',
    ],
    tests: [
      'Total testosterone',
      'Free testosterone (calculated + direct)',
      'SHBG',
      'Estradiol (sensitive)',
      'Progesterone',
      'DHEA-S',
      'Cortisol (AM serum)',
      'LH',
      'FSH',
      'Prolactin',
      'IGF-1',
      'DUTCH Complete (urine — cortisol metabolites, sex hormone metabolites, oxidative stress markers)',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 449,
      memberUSD: 369,
    },
    requiresRx: false,
    vendor: 'Rupa',
    fulfilledBy: 'Rupa Health / DUTCH (Precision Analytical)',
    tierAvailability: {
      foundation: 'addon',
      optimization: 'addon',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['low_testosterone', 'perimenopause', 'adrenal_fatigue', 'hormone_symptoms'],
    tags: ['lab', 'hormones', 'dutch', 'igf1', 'testosterone', 'estrogen'],
  },

  {
    id: 'lab-brain-biomarkers',
    slug: 'lab-brain-biomarkers',
    name: 'Brain Biomarkers Panel',
    category: 'lab',
    tagline: 'Blood-based neuro injury and neurodegeneration markers.',
    description:
      'Serum panel measuring GFAP, p-tau 217, neurofilament light chain, and BDNF to detect early neuroinjury signals, tau pathology, and neuroplasticity status.',
    mechanismBullets: [
      'GFAP (glial fibrillary acidic protein) rises with astrocytic injury and neuroinflammation',
      'p-tau 217 is the highest-specificity blood marker for Alzheimer\'s tau pathology',
      'NfL (neurofilament light) reflects axonal injury and neurodegeneration rate',
      'BDNF reflects neuroplasticity and is modulated by exercise, sleep, and peptide therapy',
    ],
    indications: [
      'Supports early detection of neurodegeneration risk and neuroinjury',
      'Helps with monitoring protocol response (BDNF, NfL) over time',
    ],
    tests: [
      'GFAP (serum)',
      'p-tau 217 (plasma)',
      'Neurofilament light chain — NfL (serum)',
      'BDNF (serum)',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 649,
      memberUSD: 549,
    },
    requiresRx: false,
    vendor: 'Quest',
    fulfilledBy: 'Quest / specialty reference lab',
    tierAvailability: {
      foundation: 'addon',
      optimization: 'addon',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['cognitive_decline', 'mci', 'dementia_risk', 'post_concussion'],
    tags: ['lab', 'neuro', 'bdnf', 'ptau', 'nfl', 'gfap'],
  },

  {
    id: 'lab-sleep-study',
    slug: 'lab-sleep-study',
    name: 'Sleep Study',
    category: 'lab',
    tagline: 'Home sleep apnea test for OSA screening without a sleep lab.',
    description:
      'WatchPAT home sleep test provides a convenient, validated screen for obstructive sleep apnea and other sleep-disordered breathing — interpreted by a sleep clinician.',
    mechanismBullets: [
      'Peripheral arterial tonometry (PAT) captures autonomic and oxygenation data during sleep',
      'Validated against polysomnography for AHI and RDI measurement',
      'At-home, single-night protocol with next-day data upload',
    ],
    indications: [
      'Helps with identifying obstructive sleep apnea as a root cause of poor sleep and cognitive decline',
      'Supports sleep architecture optimisation when other interventions are insufficient',
    ],
    tests: [
      'Apnea-hypopnea index (AHI)',
      'Respiratory disturbance index (RDI)',
      'Oxygen desaturation index (ODI)',
      'Sleep staging',
      'Heart rate variability during sleep',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 229,
      memberUSD: 189,
    },
    requiresRx: false,
    vendor: 'Quest',
    fulfilledBy: 'WatchPAT / Itamar Medical',
    tierAvailability: {
      foundation: 'addon',
      optimization: 'included',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['insomnia', 'snoring', 'daytime_fatigue', 'sleep_apnea_risk'],
    tags: ['lab', 'sleep', 'osa', 'watchpat', 'home-test'],
  },

  {
    id: 'lab-mycotoxin',
    slug: 'lab-mycotoxin',
    name: 'Mycotoxin Panel',
    category: 'lab',
    tagline: 'Urine mycotoxin screen for mold-related illness and biotoxin burden.',
    description:
      'Comprehensive urine mycotoxin panel identifying common mold-derived toxins associated with chronic fatigue, cognitive symptoms, and immune dysregulation.',
    mechanismBullets: [
      'Tests for ochratoxin A, aflatoxins, trichothecenes, zearalenone, and gliotoxin',
      'Urine provides actionable real-time excretion data versus serum',
      'Detects subclinical mold exposure not identified by standard labs',
    ],
    indications: [
      'Helps with identifying biotoxin burden as a root cause of unexplained fatigue and cognitive symptoms',
      'Supports CIRS (chronic inflammatory response syndrome) evaluation',
    ],
    tests: [
      'Ochratoxin A (urine)',
      'Aflatoxin B1, B2, G1, G2 (urine)',
      'Trichothecenes (urine)',
      'Zearalenone (urine)',
      'Gliotoxin (urine)',
      'Citrinin (urine)',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 549,
      memberUSD: 459,
    },
    requiresRx: false,
    vendor: 'Mosaic',
    fulfilledBy: 'Mosaic Diagnostics',
    tierAvailability: {
      foundation: 'na',
      optimization: 'addon',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['mold_exposure', 'chronic_fatigue', 'unexplained_symptoms'],
    tags: ['lab', 'mycotoxin', 'mold', 'biotoxin', 'cirs'],
  },

  {
    id: 'lab-heavy-metals',
    slug: 'lab-heavy-metals',
    name: 'Heavy Metals Panel',
    category: 'lab',
    tagline: 'Comprehensive heavy metal and toxic element screening.',
    description:
      'Blood and urine heavy metal panel screening for lead, mercury, arsenic, cadmium, and other toxic elements associated with cognitive and metabolic toxicity.',
    mechanismBullets: [
      'Blood metals reflect recent/ongoing exposure; urine reflects excretion and body burden',
      'Mercury speciation (organic vs inorganic) guides chelation vs dietary intervention',
      'Lead toxicity is relevant at subclinical blood levels for cognitive and cardiovascular risk',
    ],
    indications: [
      'Helps with identifying heavy metal burden as a contributor to cognitive and metabolic dysfunction',
      'Supports detox protocol design and chelation indication assessment',
    ],
    tests: [
      'Blood lead',
      'Blood mercury (total + speciation)',
      'Blood arsenic',
      'Blood cadmium',
      'Urine arsenic (speciated)',
      'Urine mercury',
      'Urine thallium',
      'Urine aluminum',
      'Urine nickel',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 549,
      memberUSD: 459,
    },
    requiresRx: false,
    vendor: 'Quest',
    fulfilledBy: 'Quest / Labcorp',
    tierAvailability: {
      foundation: 'na',
      optimization: 'addon',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['heavy_metal_exposure', 'cognitive_decline', 'unexplained_symptoms'],
    tags: ['lab', 'heavy-metals', 'mercury', 'lead', 'detox'],
  },

  {
    id: 'lab-advanced-cardiovascular',
    slug: 'lab-advanced-cardiovascular',
    name: 'Advanced Cardiovascular Panel',
    category: 'lab',
    tagline: 'Lp(a), LDL particle number, and oxidised LDL for residual cardiovascular risk.',
    description:
      'Advanced lipid panel beyond standard cholesterol — Lp(a), LDL-P (NMR), small dense LDL, and oxidised LDL to characterise residual cardiovascular risk not captured by standard lipid panels.',
    mechanismBullets: [
      'Lp(a) is a genetically determined independent cardiovascular risk factor missed by standard panels',
      'LDL particle number (LDL-P) is a stronger predictor of ASCVD events than LDL-C',
      'Small dense LDL (sdLDL) is the most atherogenic LDL subfraction',
      'Oxidised LDL (oxLDL) directly quantifies lipid oxidation and vascular injury signalling',
    ],
    indications: [
      'Supports cardiovascular risk stratification beyond standard lipid panels',
      'Helps with identifying residual risk in patients with "normal" cholesterol',
    ],
    tests: [
      'Lp(a) — lipoprotein(a)',
      'LDL particle number — LDL-P (NMR)',
      'Small dense LDL — sdLDL',
      'Oxidised LDL — oxLDL',
      'HDL subfractions',
      'ApoB / ApoA-1 ratio',
    ],
    pricing: {
      type: 'one-time',
      retailUSD: 349,
      memberUSD: 289,
    },
    requiresRx: false,
    vendor: 'Quest',
    fulfilledBy: 'Quest / Labcorp',
    tierAvailability: {
      foundation: 'addon',
      optimization: 'addon',
      longevity: 'included',
      concierge: 'included',
    },
    triggersFromIntake: ['cardiovascular_risk', 'family_heart_history', 'high_ldl'],
    tags: ['lab', 'cardiovascular', 'lpa', 'ldl-p', 'advanced-lipid'],
  },
];
